version: '3.8'

services:
  catalog-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/catalog
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
