version: '3.8'
services:
  catalog-service:
    image: catalog
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    links:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"